# Generated by Django 2.1.3 on 2019-01-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
